apiVersion: apps/v1
kind: Deployment
metadata:
  name: front50
  namespace: spinnaker
spec:
  replicas: 1
  template:
    spec:
      serviceAccount: spinnaker-service-account-front50
      serviceAccountName: spinnaker-service-account-front50
      securityContext:
        fsGroup: 100
      