apiVersion: v1
kind: Service
metadata:
  name: gate
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-security-groups: <SG_ID>
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN>
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      $patch: delete
    - port: 443
      protocol: TCP
      targetPort: 8084
  