apiVersion: v1
kind: Service
metadata:
  name: deck
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-security-groups: <SG>
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN>
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      $patch: delete
    - port: 443
      protocol: TCP
      targetPort: 9000